##### BEGIN external/Dockerfile/iamge-header #####
FROM nginx:1.17.3
##### END external/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
USER root
RUN apt-get update && apt-get install -y gettext && apt-get install -y jq && rm -rf /var/cache/apt/*
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/git-repository/
##### END external/Dockerfile/conteco #####

##### BEGIN external/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="nginx" \
      io.vcweb.tag="1.17.3" \
      io.vcweb.base="nginx:1.17.3" \
      io.vcweb.build="external" \
      io.vcweb.label="External Nginx image" \
      io.vcweb.description="Import of external official Nginx image into the ContEco ecosystem." \
      io.vcweb.repository="/conteco/git-repository" 
##### END external/Dockerfile/labels-footer #####
