##### BEGIN external/Dockerfile/image-header #####
FROM nginx:1.19.3
##### END external/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
USER root
RUN apt-get update && apt-get install -y --force-yes gettext && apt-get install -y --force-yes wget && rm -rf /var/cache/apt/*
RUN wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq && cp jq /usr/bin
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/repo/
##### END external/Dockerfile/conteco #####

##### BEGIN external/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="nginx" \
      io.vcweb.tag="1.19.3" \
      io.vcweb.base="nginx:1.19.3" \
      io.vcweb.build="external" \
      io.vcweb.label="external.nginx - ContEco" \
      io.vcweb.description="Nginx image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo"
##### END external/Dockerfile/labels-footer #####
