##### BEGIN external/Dockerfile/image-header #####
FROM nginx:1.17.3
##### END external/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
USER root
RUN apt-get update && apt-get install -y gettext && apt-get install -y jq && rm -rf /var/cache/apt/*
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/repo/
##### END external/Dockerfile/conteco #####

##### BEGIN external/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="nginx" \
      io.vcweb.tag="1.17.3" \
      io.vcweb.base="nginx:1.17.3" \
      io.vcweb.build="external" \
      io.vcweb.label="external.nginx - ContEco" \
      io.vcweb.description="Nginx image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo" 
##### END external/Dockerfile/labels-footer #####
