#!/usr/bin/env bash

export CONTECO_LABEL="external.nginx - ContEco"
export CONTECO_DESCRIPTION="Nginx image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="nginx"
export CONTECO_TAG="1.19.3"

export CONTECO_BASE="${CONTECO_NAME}:${CONTECO_TAG}"
export CONTECO_BUILD="external"
