#!/usr/bin/env bash

export CONTECO_LABEL="External Nginx image"
export CONTECO_DESCRIPTION="Import of external official Nginx image into the ContEco ecosystem."

export CONTECO_TYPE="external"
export CONTECO_NAME="nginx"
export CONTECO_TAG="1.15.12"

export CONTECO_BUILD="external"
