#!/usr/bin/env bash

export CONTECO_LABEL="External Nginx image"
export CONTECO_DESCRIPTION="Import of external official Nginx image into the ContEco ecosystem."

export CONTECO_TYPE="external"
export CONTECO_NAME="nginx"
export CONTECO_TAG="1.17.3"

export CONTECO_BASE="${CONTECO_NAME}:${CONTECO_TAG}"
export CONTECO_BUILD="external"
